import { db } from "../../lib/db/src/index.js";
import { menuItemsTable } from "../../lib/db/src/schema/menu_items.js";

async function seed() {
  console.log("Seeding menu items...");

  const items = [
    {
      name: "Classic Wada Pav",
      description: "Traditional Mumbai-style spiced potato fritter in soft bun with chutneys",
      price: 40,
      category: "Vada Pav",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2017/11/wada-pav-recipe.jpg",
      prepTimeMinutes: 8,
      isAvailable: true,
      isVeg: true,
      calories: 280,
    },
    {
      name: "Cheese Burst Wada Pav",
      description: "Classic vada pav loaded with melted cheese and tangy chutneys",
      price: 50,
      category: "Vada Pav",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/4fb/30f30c6aeb85ee7be0359f1e1fb3a4fb.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: true,
      calories: 340,
    },
    {
      name: "Schezwan Wada Pav",
      description: "Spicy schezwan sauce with crispy vada in soft pav",
      price: 55,
      category: "Vada Pav",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/4fa/0cc689cf93eb1293f778731b8162f4fa.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: true,
      calories: 310,
    },
    {
      name: "Maharaja Wada / Cheeses",
      description: "Loaded vada pav with multiple cheese varieties and special toppings",
      price: 75,
      category: "Vada Pav",
      imageUrl: "https://b.zmtcdn.com/data/pictures/chains/5/19302635/f6cb40ca70919fb59f427f7112015fa7.jpg",
      prepTimeMinutes: 12,
      isAvailable: true,
      isVeg: true,
      calories: 420,
    },
    {
      name: "Sabudana Wada 2 Pcs",
      description: "Crispy sabudana (tapioca pearl) fritters, perfect tea-time snack",
      price: 45,
      category: "Vada Pav",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/02/sabudana-vada-recipe-1.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 220,
    },
    {
      name: "Veg. Burger",
      description: "Classic vegetable patty burger with fresh lettuce and mayo",
      price: 65,
      category: "Burger",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2015/08/veg-burger.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: true,
      calories: 380,
    },
    {
      name: "Paneer Burger",
      description: "Grilled paneer patty with onions, tomatoes and special sauce",
      price: 75,
      category: "Burger",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/14a/77c05051a81e938996e3a9fa93e2114a.jpg",
      prepTimeMinutes: 12,
      isAvailable: true,
      isVeg: true,
      calories: 420,
    },
    {
      name: "Cheese Burger Single",
      description: "Juicy veg patty with melted cheese and fresh vegetables",
      price: 85,
      category: "Burger",
      imageUrl: "https://www.cookwithmanali.com/wp-content/uploads/2021/04/Cheese-Burger.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: true,
      calories: 450,
    },
    {
      name: "Cheese Burger Double",
      description: "Double patty loaded with cheese and premium toppings",
      price: 105,
      category: "Burger",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2016/02/burger-recipe.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 620,
    },
    {
      name: "Veg. Roll",
      description: "Mixed vegetables wrapped in soft paratha with tangy sauces",
      price: 75,
      category: "Roll",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/f13/35e8d98d24956ca0b29849fa024e3f13.jpg",
      prepTimeMinutes: 12,
      isAvailable: true,
      isVeg: true,
      calories: 340,
    },
    {
      name: "Paneer Roll",
      description: "Soft paneer cubes with onions and peppers in rolled paratha",
      price: 75,
      category: "Roll",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2014/01/paneer-kathi-roll-recipe-1.jpg",
      prepTimeMinutes: 12,
      isAvailable: true,
      isVeg: true,
      calories: 380,
    },
    {
      name: "Sweet Corn Roll",
      description: "Creamy sweet corn filling wrapped in crispy roll",
      price: 75,
      category: "Roll",
      imageUrl: "https://www.cookwithmanali.com/wp-content/uploads/2018/05/Sweet-Corn-Kathi-Roll.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: true,
      calories: 320,
    },
    {
      name: "Sweet Cheese Roll",
      description: "Sweet corn and melted cheese in soft roll",
      price: 95,
      category: "Roll",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/a39/54e1957c79db28b9d07df687f8972a39.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: true,
      calories: 390,
    },
    {
      name: "Mushroom Roll",
      description: "Sautéed mushrooms with herbs in paratha wrap",
      price: 75,
      category: "Roll",
      imageUrl: "https://www.spiceupthecurry.com/wp-content/uploads/2020/08/mushroom-kathi-roll-recipe-1.jpg",
      prepTimeMinutes: 12,
      isAvailable: true,
      isVeg: true,
      calories: 360,
    },
    {
      name: "Egg Roll",
      description: "Scrambled eggs with onions and spices in soft roll",
      price: 75,
      category: "Roll",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2019/05/Egg-Roll-2-3.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: false,
      calories: 340,
    },
    {
      name: "Schezwan Sandwich",
      description: "Spicy schezwan sauce with vegetables in grilled sandwich",
      price: 55,
      category: "Sandwich",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/04/schezwan-sandwich-recipe-1.jpg",
      prepTimeMinutes: 8,
      isAvailable: true,
      isVeg: true,
      calories: 290,
    },
    {
      name: "Veg. Sandwich",
      description: "Fresh vegetables with mayo and mint chutney in toasted bread",
      price: 50,
      category: "Sandwich",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2017/08/veg-sandwich-recipe.jpg",
      prepTimeMinutes: 7,
      isAvailable: true,
      isVeg: true,
      calories: 260,
    },
    {
      name: "Cheese Sandwich",
      description: "Loaded cheese sandwich with crispy grilled exterior",
      price: 55,
      category: "Sandwich",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/4c2/481be92dca32607fa66542d8ca2814c2.jpg",
      prepTimeMinutes: 8,
      isAvailable: true,
      isVeg: true,
      calories: 320,
    },
    {
      name: "Paneer Sandwich",
      description: "Grilled paneer with vegetables in toasted sandwich",
      price: 65,
      category: "Sandwich",
      imageUrl: "https://www.cookwithmanali.com/wp-content/uploads/2019/03/Paneer-Sandwich.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: true,
      calories: 350,
    },
    {
      name: "Paneer with Chee. Sandwich",
      description: "Paneer and cheese combination in perfectly grilled sandwich",
      price: 85,
      category: "Sandwich",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2020/07/Paneer-Cheese-Sandwich-2-3.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: true,
      calories: 410,
    },
    {
      name: "Sweet Corn Sandwich",
      description: "Creamy sweet corn filling in toasted sandwich",
      price: 75,
      category: "Sandwich",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2014/01/sweet-corn-sandwich-recipe-1.jpg",
      prepTimeMinutes: 8,
      isAvailable: true,
      isVeg: true,
      calories: 300,
    },
    {
      name: "Mushroom Sandwich",
      description: "Sautéed mushrooms with cheese in grilled sandwich",
      price: 65,
      category: "Sandwich",
      imageUrl: "https://www.spiceupthecurry.com/wp-content/uploads/2020/07/mushroom-sandwich-recipe-1.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: true,
      calories: 330,
    },
    {
      name: "Sweet Corn Pizza",
      description: "Wood-fired pizza topped with sweet corn and cheese",
      price: 85,
      category: "Pizza",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/176/676a6e5bc9d5c3175f3a0db90840b176.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 520,
    },
    {
      name: "Paneer Pizza",
      description: "Paneer chunks with bell peppers and onions on pizza base",
      price: 85,
      category: "Pizza",
      imageUrl: "https://www.cookwithmanali.com/wp-content/uploads/2015/07/Paneer-Pizza.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 550,
    },
    {
      name: "Mushroom Pizza",
      description: "Fresh mushrooms with herbs and cheese on crispy crust",
      price: 85,
      category: "Pizza",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2020/01/mushroom-pizza-recipe.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 540,
    },
    {
      name: "Baby Corn Pizza",
      description: "Baby corn with capsicum and special pizza sauce",
      price: 85,
      category: "Pizza",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/9d2/73fe4925bd3d25642a8a8fc4b95bf9d2.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 530,
    },
    {
      name: "Egg Pizza",
      description: "Egg with vegetables and cheese on pizza base",
      price: 85,
      category: "Pizza",
      imageUrl: "https://www.recipetineats.com/wp-content/uploads/2020/05/Breakfast-Pizza_5.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: false,
      calories: 560,
    },
    {
      name: "Tomato Pizza",
      description: "Fresh tomatoes with basil and mozzarella on thin crust",
      price: 85,
      category: "Pizza",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2020/03/tomato-pizza-recipe.jpg",
      prepTimeMinutes: 16,
      isAvailable: true,
      isVeg: true,
      calories: 510,
    },
    {
      name: "Noodles Pizza",
      description: "Fusion pizza with noodles and vegetables",
      price: 85,
      category: "Pizza",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/5bb/b6d6f51be02422e6bbf451eb9927b5bb.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 590,
    },
    {
      name: "Gobi Pizza",
      description: "Spiced cauliflower with cheese on pizza base",
      price: 85,
      category: "Pizza",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/03/gobi-pizza-recipe.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 520,
    },
    {
      name: "Schezwan Pizza",
      description: "Spicy schezwan sauce with mixed vegetables on pizza",
      price: 90,
      category: "Pizza",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2020/08/Schezwan-Pizza.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 570,
    },
    {
      name: "Strawberry Milk Shake",
      description: "Fresh strawberries blended with creamy milk and ice cream",
      price: 50,
      category: "Milk Shakes",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2016/05/strawberry-milkshake-recipe.jpg",
      prepTimeMinutes: 5,
      isAvailable: true,
      isVeg: true,
      calories: 280,
    },
    {
      name: "Vanilla Milk Shake",
      description: "Classic vanilla ice cream blended with milk",
      price: 50,
      category: "Milk Shakes",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2014/06/vanilla-milkshake-recipe.jpg",
      prepTimeMinutes: 4,
      isAvailable: true,
      isVeg: true,
      calories: 260,
    },
    {
      name: "Chocolate Milk Shake",
      description: "Rich chocolate ice cream blended with milk and chocolate syrup",
      price: 50,
      category: "Milk Shakes",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2019/03/chocolate-milkshake-recipe.jpg",
      prepTimeMinutes: 5,
      isAvailable: true,
      isVeg: true,
      calories: 310,
    },
    {
      name: "Butter Scotch Shake",
      description: "Butterscotch ice cream with caramel sauce",
      price: 50,
      category: "Milk Shakes",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/butterscotch-shake.jpg",
      prepTimeMinutes: 5,
      isAvailable: true,
      isVeg: true,
      calories: 290,
    },
    {
      name: "Mango Milk Shake",
      description: "Fresh Alphonso mango blended with creamy milk",
      price: 60,
      category: "Milk Shakes",
      imageUrl: "https://www.yellowthyme.com/wp-content/uploads/2023/03/Mango-Milkshake-08570.jpg",
      prepTimeMinutes: 5,
      isAvailable: true,
      isVeg: true,
      calories: 300,
    },
    {
      name: "Mixed Fruit Shake",
      description: "Seasonal fresh fruits blended with milk and ice cream",
      price: 60,
      category: "Milk Shakes",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/05/fruit-shake-recipe.jpg",
      prepTimeMinutes: 6,
      isAvailable: true,
      isVeg: true,
      calories: 320,
    },
    {
      name: "Pista Badam Shake",
      description: "Pistachio and almond blended with creamy milk",
      price: 60,
      category: "Milk Shakes",
      imageUrl: "https://www.cookwithmanali.com/wp-content/uploads/2018/05/Badam-Milk.jpg",
      prepTimeMinutes: 5,
      isAvailable: true,
      isVeg: true,
      calories: 340,
    },
    {
      name: "Black Currant Shake",
      description: "Rich black currant ice cream shake",
      price: 60,
      category: "Milk Shakes",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/477/2ee8df944ba0e08f6580cb4e995a9477.jpg",
      prepTimeMinutes: 4,
      isAvailable: true,
      isVeg: true,
      calories: 290,
    },
    {
      name: "Oreo Milk Shake",
      description: "Crushed oreo cookies blended with vanilla ice cream",
      price: 80,
      category: "Milk Shakes",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2023/01/oreo-milkshake-recipe.jpg",
      prepTimeMinutes: 5,
      isAvailable: true,
      isVeg: true,
      calories: 380,
    },
    {
      name: "Gobi Manchurian",
      description: "Crispy cauliflower florets in tangy Indo-Chinese sauce",
      price: 45,
      category: "Gobi Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2013/12/gobi-manchurian-recipe-1.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 280,
    },
    {
      name: "Gobi Chilly",
      description: "Spicy cauliflower with green chilies and soy sauce",
      price: 50,
      category: "Gobi Items",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2019/06/Gobi-Chilli-2-3.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 260,
    },
    {
      name: "Gobi Dry",
      description: "Crispy dry cauliflower with aromatic spices",
      price: 60,
      category: "Gobi Items",
      imageUrl: "https://www.spiceupthecurry.com/wp-content/uploads/2018/07/gobi-dry-recipe-1.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 240,
    },
    {
      name: "Gobi Pepper Dry",
      description: "Black pepper flavored crispy cauliflower",
      price: 65,
      category: "Gobi Items",
      imageUrl: "https://www.cookwithmanali.com/wp-content/uploads/2018/03/Gobi-Pepper-Fry.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 270,
    },
    {
      name: "Gobi 65",
      description: "South Indian style spicy fried cauliflower",
      price: 70,
      category: "Gobi Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2020/11/gobi-65-recipe-1.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 310,
    },
    {
      name: "Gobi Kabab",
      description: "Spiced cauliflower kebabs with herbs",
      price: 80,
      category: "Gobi Items",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/09/gobi-kebab.jpg",
      prepTimeMinutes: 25,
      isAvailable: true,
      isVeg: true,
      calories: 290,
    },
    {
      name: "Gobi Pakoda",
      description: "Cauliflower fritters in chickpea batter",
      price: 80,
      category: "Gobi Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2014/01/gobi-pakora-recipe-1.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 250,
    },
    {
      name: "Gobi Peri Peri Dry",
      description: "Peri peri spiced crispy cauliflower",
      price: 80,
      category: "Gobi Items",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2020/08/Peri-Peri-Gobi.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 280,
    },
    {
      name: "Babycorn Manchurian",
      description: "Crispy baby corn in tangy Manchurian sauce",
      price: 65,
      category: "Babycorn Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2020/06/baby-corn-manchurian-1.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 310,
    },
    {
      name: "Babycorn Chilly",
      description: "Spicy baby corn with green chilies and bell peppers",
      price: 70,
      category: "Babycorn Items",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2020/07/Baby-Corn-Chilli-2-3.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 290,
    },
    {
      name: "Babycorn Dry",
      description: "Crispy fried baby corn with aromatic spices",
      price: 70,
      category: "Babycorn Items",
      imageUrl: "https://www.cookwithmanali.com/wp-content/uploads/2018/07/Baby-Corn-Dry.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 270,
    },
    {
      name: "Babycorn Pepper Dry",
      description: "Black pepper flavored crispy baby corn",
      price: 75,
      category: "Babycorn Items",
      imageUrl: "https://www.spiceupthecurry.com/wp-content/uploads/2019/08/baby-corn-pepper-fry-1.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 300,
    },
    {
      name: "Babycorn 65",
      description: "Spicy South Indian style fried baby corn",
      price: 80,
      category: "Babycorn Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2020/11/baby-corn-65-recipe.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 330,
    },
    {
      name: "Babycorn Kabab",
      description: "Marinated baby corn kebabs with herbs",
      price: 80,
      category: "Babycorn Items",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/baby-corn-kebab.jpg",
      prepTimeMinutes: 25,
      isAvailable: true,
      isVeg: true,
      calories: 310,
    },
    {
      name: "Babycorn Pakoda",
      description: "Baby corn fritters in crispy chickpea batter",
      price: 90,
      category: "Babycorn Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2020/11/baby-corn-pakora.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 280,
    },
    {
      name: "Babycorn Peri Peri Dry",
      description: "Peri peri spiced crispy baby corn",
      price: 80,
      category: "Babycorn Items",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2021/03/Peri-Peri-Baby-Corn.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 300,
    },
    {
      name: "Mushroom Manchurian",
      description: "Crispy mushrooms in tangy Indo-Chinese sauce",
      price: 65,
      category: "Mushroom Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2020/06/mushroom-manchurian-1.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 290,
    },
    {
      name: "Mushroom Chilly",
      description: "Spicy mushrooms with green chilies and peppers",
      price: 70,
      category: "Mushroom Items",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2020/07/Mushroom-Chilli-2-3.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 270,
    },
    {
      name: "Mushroom Dry",
      description: "Sautéed mushrooms with aromatic spices",
      price: 80,
      category: "Mushroom Items",
      imageUrl: "https://www.spiceupthecurry.com/wp-content/uploads/2020/08/mushroom-dry-fry-1.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 250,
    },
    {
      name: "Mushroom Pepper Dry",
      description: "Black pepper flavored sautéed mushrooms",
      price: 85,
      category: "Mushroom Items",
      imageUrl: "https://www.cookwithmanali.com/wp-content/uploads/2018/09/Mushroom-Pepper-Fry.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 280,
    },
    {
      name: "Mushroom 65",
      description: "Spicy South Indian style fried mushrooms",
      price: 90,
      category: "Mushroom Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2020/11/mushroom-65-recipe-1.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 310,
    },
    {
      name: "Mushroom Kabab",
      description: "Marinated mushroom kebabs with herbs and spices",
      price: 80,
      category: "Mushroom Items",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/mushroom-kebab.jpg",
      prepTimeMinutes: 25,
      isAvailable: true,
      isVeg: true,
      calories: 290,
    },
    {
      name: "Mushroom Pakoda",
      description: "Mushroom fritters in crispy chickpea batter",
      price: 80,
      category: "Mushroom Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2020/11/mushroom-pakora.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 270,
    },
    {
      name: "Mushroom Peri Peri Dry",
      description: "Peri peri spiced crispy mushrooms",
      price: 80,
      category: "Mushroom Items",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2021/03/Peri-Peri-Mushroom.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 280,
    },
    {
      name: "Paneer Manchurian",
      description: "Crispy paneer cubes in tangy Manchurian sauce",
      price: 65,
      category: "Paneer Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2020/06/paneer-manchurian-1.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 350,
    },
    {
      name: "Paneer Chilly",
      description: "Spicy paneer with green chilies and bell peppers",
      price: 75,
      category: "Paneer Items",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2019/08/Chilli-Paneer-2-3.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 330,
    },
    {
      name: "Paneer Dry",
      description: "Crispy fried paneer with aromatic spices",
      price: 80,
      category: "Paneer Items",
      imageUrl: "https://www.spiceupthecurry.com/wp-content/uploads/2020/06/paneer-dry-fry-1.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 310,
    },
    {
      name: "Paneer Pepper Dry",
      description: "Black pepper flavored crispy paneer",
      price: 85,
      category: "Paneer Items",
      imageUrl: "https://www.cookwithmanali.com/wp-content/uploads/2018/08/paneer-pepper-fry.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 340,
    },
    {
      name: "Paneer 65",
      description: "Spicy South Indian style fried paneer",
      price: 90,
      category: "Paneer Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2020/11/paneer-65-recipe-1.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 370,
    },
    {
      name: "Paneer Kabab",
      description: "Marinated paneer kebabs with herbs and spices",
      price: 80,
      category: "Paneer Items",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/paneer-tikka-kebab.jpg",
      prepTimeMinutes: 25,
      isAvailable: true,
      isVeg: true,
      calories: 350,
    },
    {
      name: "Paneer Pakoda",
      description: "Paneer fritters in crispy chickpea batter",
      price: 80,
      category: "Paneer Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2014/01/paneer-pakora-recipe-1.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 330,
    },
    {
      name: "Paneer Peri Peri Dry",
      description: "Peri peri spiced crispy paneer cubes",
      price: 80,
      category: "Paneer Items",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2021/03/Peri-Peri-Paneer.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 340,
    },
    {
      name: "Bread Omelette",
      description: "Classic bread slices with fluffy egg omelette",
      price: 60,
      category: "Snacks",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/10/bread-omelette.jpg",
      prepTimeMinutes: 8,
      isAvailable: true,
      isVeg: false,
      calories: 280,
    },
    {
      name: "Alu Tikki",
      description: "Crispy potato patties with chutneys",
      price: 70,
      category: "Snacks",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2013/11/aloo-tikki-recipe-1.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 240,
    },
    {
      name: "Smile",
      description: "Crispy smile-shaped potato snacks",
      price: 70,
      category: "Snacks",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/477/f7cbe540a996da6042dbff2f06b49477.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: true,
      calories: 220,
    },
    {
      name: "French Chips",
      description: "Classic crispy french fries",
      price: 55,
      category: "Snacks",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2018/05/French-Fries-2-3.jpg",
      prepTimeMinutes: 12,
      isAvailable: true,
      isVeg: true,
      calories: 310,
    },
    {
      name: "Finger Chips Peri Peri",
      description: "Crispy fries seasoned with peri peri spice",
      price: 65,
      category: "Snacks",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2020/05/Peri-Peri-French-Fries.jpg",
      prepTimeMinutes: 12,
      isAvailable: true,
      isVeg: true,
      calories: 330,
    },
    {
      name: "Pav Bhaji",
      description: "Spiced vegetable curry served with buttered pav bread",
      price: 45,
      category: "Snacks",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/04/pav-bhaji-recipe-1.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 380,
    },
    {
      name: "Alu Twister",
      description: "Crispy potato spirals with spices",
      price: 50,
      category: "Snacks",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/3d2/5482e99fa996dbbb42dbff2f06b493d2.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: true,
      calories: 260,
    },
    {
      name: "Schezwan Curry",
      description: "Spicy Indo-Chinese style vegetable curry",
      price: 85,
      category: "Curry Items",
      imageUrl: "https://www.whiskaffair.com/wp-content/uploads/2020/08/Schezwan-Curry.jpg",
      prepTimeMinutes: 25,
      isAvailable: true,
      isVeg: true,
      calories: 320,
    },
    {
      name: "Paneer Butter Curry",
      description: "Creamy tomato gravy with soft paneer cubes",
      price: 85,
      category: "Curry Items",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/15b/9871fcb6eb85ee7be0359f1e1fb3a15b.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 410,
    },
    {
      name: "Veg Masala",
      description: "Mixed vegetables in rich masala gravy",
      price: 85,
      category: "Curry Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2020/06/veg-curry-1.jpg",
      prepTimeMinutes: 25,
      isAvailable: true,
      isVeg: true,
      calories: 290,
    },
    {
      name: "Veg Curry",
      description: "Mixed vegetables in flavorful curry sauce",
      price: 90,
      category: "Curry Items",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/08/vegetable-curry-recipe.jpg",
      prepTimeMinutes: 25,
      isAvailable: true,
      isVeg: true,
      calories: 270,
    },
    {
      name: "Kaju Paneer Curry",
      description: "Cashew and paneer in creamy rich gravy",
      price: 105,
      category: "Curry Items",
      imageUrl: "https://www.cookwithmanali.com/wp-content/uploads/2017/07/Kaju-Paneer-Recipe.jpg",
      prepTimeMinutes: 30,
      isAvailable: true,
      isVeg: true,
      calories: 450,
    },
    {
      name: "1 Boiled Egg",
      description: "Perfectly boiled egg",
      price: 15,
      category: "Egg Items",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/10/boiled-egg-recipe.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: false,
      calories: 70,
    },
    {
      name: "Omelette",
      description: "Fluffy omelette with onions and spices",
      price: 45,
      category: "Egg Items",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/10/masala-omelette-recipe.jpg",
      prepTimeMinutes: 8,
      isAvailable: true,
      isVeg: false,
      calories: 180,
    },
    {
      name: "Egg Burji",
      description: "Scrambled eggs with onions, tomatoes and spices",
      price: 65,
      category: "Egg Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2014/11/egg-bhurji-recipe-1.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: false,
      calories: 220,
    },
    {
      name: "Boiled Egg Fry",
      description: "Boiled egg halves fried with spices",
      price: 75,
      category: "Egg Items",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/egg-fry-recipe.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: false,
      calories: 190,
    },
    {
      name: "Egg Curry",
      description: "Boiled eggs in spicy curry gravy",
      price: 85,
      category: "Egg Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2014/05/egg-curry-recipe-1.jpg",
      prepTimeMinutes: 25,
      isAvailable: true,
      isVeg: false,
      calories: 280,
    },
    {
      name: "Egg Masala Fry",
      description: "Fried eggs with masala spices",
      price: 85,
      category: "Egg Items",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/egg-masala-fry.jpg",
      prepTimeMinutes: 12,
      isAvailable: true,
      isVeg: false,
      calories: 240,
    },
    {
      name: "2 Idli",
      description: "Soft steamed rice cakes served with sambar and chutney",
      price: 25,
      category: "Tiffin Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/06/idli-recipe-1.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 150,
    },
    {
      name: "Vada",
      description: "Crispy lentil donuts served with sambar and chutney",
      price: 20,
      category: "Tiffin Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2013/11/medu-vada-recipe-1.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 180,
    },
    {
      name: "2 Idli - 1 Vada",
      description: "Combo of idli and vada with sambar and chutneys",
      price: 30,
      category: "Tiffin Items",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/idli-vada-combo.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 240,
    },
    {
      name: "Puri",
      description: "Fluffy deep-fried bread served with potato curry",
      price: 35,
      category: "Tiffin Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2013/07/puri-recipe-1.jpg",
      prepTimeMinutes: 18,
      isAvailable: true,
      isVeg: true,
      calories: 320,
    },
    {
      name: "Vaggani Mirchi",
      description: "Spicy fried green chilies with chickpea flour coating",
      price: 35,
      category: "Tiffin Items",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/08/mirchi-bajji.jpg",
      prepTimeMinutes: 12,
      isAvailable: true,
      isVeg: true,
      calories: 140,
    },
    {
      name: "1 Idli",
      description: "Single soft steamed rice cake",
      price: 15,
      category: "Tiffin Items",
      imageUrl: "https://b.zmtcdn.com/data/dish_photos/01b/ccdebc6aeb85ee7be0359f1e1fb3a01b.jpg",
      prepTimeMinutes: 10,
      isAvailable: true,
      isVeg: true,
      calories: 75,
    },
    {
      name: "1 Idli 1 Vada",
      description: "Combo of one idli and one vada",
      price: 30,
      category: "Tiffin Items",
      imageUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/idli-vada.jpg",
      prepTimeMinutes: 12,
      isAvailable: true,
      isVeg: true,
      calories: 165,
    },
    {
      name: "1 Puri",
      description: "Single fluffy deep-fried bread",
      price: 15,
      category: "Tiffin Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2013/07/puri-bhaji.jpg",
      prepTimeMinutes: 8,
      isAvailable: true,
      isVeg: true,
      calories: 90,
    },
    {
      name: "Dahi Vada",
      description: "Lentil vadas soaked in creamy yogurt with chutneys",
      price: 30,
      category: "Tiffin Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2014/05/dahi-vada-recipe-1.jpg",
      prepTimeMinutes: 20,
      isAvailable: true,
      isVeg: true,
      calories: 220,
    },
    {
      name: "Aloo Parota",
      description: "Stuffed paratha with spiced potato filling",
      price: 35,
      category: "Tiffin Items",
      imageUrl: "https://www.vegrecipesofindia.com/wp-content/uploads/2019/08/aloo-paratha-recipe-1.jpg",
      prepTimeMinutes: 15,
      isAvailable: true,
      isVeg: true,
      calories: 290,
    },
  ];

  await db.delete(menuItemsTable);
  await db.insert(menuItemsTable).values(items);
  console.log("Seeded menu items successfully!");
}

seed().catch(console.error);